### PR TITLE
Running multiple devices

### PR DESCRIPTION
**Pull request by mmarkelov**
https://github.com/mmarkelov/jest-playwright/issues/19#issuecomment-584937549

### CODE REVIEW

**Comment by mxschmitt** [comment]
cool!

**Comment by mmarkelov** [comment]
I suppose that we should able run tests for **devices** without defined **browsers** in config.
Cases:
- We defined **browsers** and **devices**:
```js
module.exports = {
     browsers: [ 'chromium', 'firefox'],
     devices: ['iPhone 6', 'Pixel 2']
}
```
For this case we need run 4 tests: 
1. chromium and iPhone 6
2. chromium and Pixel 2
3. firefox and iPhone 6
4. firefox and Pixel 2

- We defined **devices**:
```js
module.exports = {
     devices: ['iPhone 6', 'Pixel 2']
}
```

If we are using standalone version, for example **playwright-webkit**, we should run 2 tests:
1. webkit and iPhone 6
2. webkit and Pixel 2

But I'm not sure what to do for **playwright**. Should it run for default **chromium** browser? Also browser can be defined with env variable

**Comment by mxschmitt** [comment]
> I suppose that we should able run tests for **devices** without defined **browsers** in config.
> Cases:
> 
> * We defined **browsers** and **devices**:
> 
> ```js
> module.exports = {
>      browsers: [ 'chromium', 'firefox'],
>      devices: ['iPhone 6', 'Pixel 2']
> }
> ```
> 
> For this case we need run 4 tests:
> 
> 1. chromium and iPhone 6
> 2. chromium and Pixel 2
> 3. firefox and iPhone 6
> 4. firefox and Pixel 2
> 
> * We defined **devices**:
> 
> ```js
> module.exports = {
>      devices: ['iPhone 6', 'Pixel 2']
> }
> ```
> 
> If we are using standalone version, for example **playwright-webkit**, we should run 2 tests:
> 
> 1. webkit and iPhone 6
> 2. webkit and Pixel 2
> 
> But I'm not sure what to do for **playwright**. Should it run for default **chromium** browser? Also browser can be defined with env variable

If they are using `playwright` I would only run it on `chromium` as you said. So `chromium` is the default. If they specify the `browsers` setting manually, then it will be overwritten.

**Comment by mmarkelov** [comment]
@mxschmitt I think I'm done here

**Pull request merged**
